### ISSUE TITLE
Custom propTypes validators

### ISSUE THREAD

**Issue by eps1lon** [merceyz/typescript-to-proptypes#1]
How could I allow custom validators that cannot be expressed with static types?

For example certain components might map+clone their children in which case `React.Fragment` blocks this composition. I would like to validate that none of the children is a `React.Fragment` which is currently impossible to express with TypeScript and needs a [custom propTypes validator](https://www.npmjs.com/package/prop-types#usage).

**Comment by merceyz** [comment]
Turns out I wasn't watching this repository, so sorry about the slow response.

---

This could be done by adding a tag to the JSDoc of the prop you want this validator on and a hook into the `generate` function to handle said tag. There is currently no way to hook into the `generate` function, but i'll implement it if you want to take this route.

**Comment by eps1lon** [comment]
Currently looking at this again. I wouldn't want to pollute the JSDoc with custom tags. I think a simple mapping pipeline would be sufficient `generate(theTextTypescriptToPropTypesGenerated, thePropNode): string`.

For our use case I would move the text specifying that we need an element accepting a ref to the jsdoc and then check in the generate pipelin if the jsdoc contains this hint. If so then return `elementTypeAcceptingRef`.
